enum WindowsEvents {
  CART_DATA = 'CART_DATA',
  CART_HEADER = 'CART_HEADER',
  TOGGLE_CART_ASIDE = 'TOGGLE_CART_ASIDE',
  ADD_PRODUCT_IN_CART = 'ADD_PRODUCT_IN_CART',
}

export default WindowsEvents;
